[package]
name = "piece"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bevy_ecs = { version = "0.12.1", default-features = false }
derive_more = "0.99.17"
include_dir = "0.7.3"
indexmap = { version = "2.1.0", features = [ "serde" ] }
indoc = "2.0.4"
protobuf = "3.3.0"
rand = "0.8.5"
ratatui = "0.24.0"
rusqlite = { version = "0.30.0", features = [ "bundled" ] }
scopeguard = "1.2.0"
serde = { version = "1.0.193", features = [ "derive" ] }
serde_json = "1.0.108"


[build-dependencies]
protobuf-codegen = "3.3.0"

[dev-dependencies]
pretty_assertions = "1.4.0"