[package]
name = "piece"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bevy_ecs = "0.12.0"
derive_more = "0.99.17"
include_dir = "0.7.3"
indexmap = { version = "2.1.0", features = ["serde"] }
rand = "0.8.5"
scopeguard = "1.2.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_yaml = "0.9.27"
