[package]
name = "piece"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bevy_ecs = { version = "0.12.1", default-features = false }
derive_more = "0.99.17"
include_dir = "0.7.3"
indexmap = { version = "2.1.0", features = [ "serde" ] }
itertools = "0.12.0"
paste = "1.0.14"
protobuf = "3.3.0"
rand = "0.8.5"
scopeguard = "1.2.0"
strum = { version = "0.25.0", features = [ "derive" ] }


[build-dependencies]
protobuf-codegen = "3.3.0"

[dev-dependencies]
pretty_assertions = "1.4.0"
