[package]
name = "piece"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
rand = "0.8.5"
scopeguard = "1.2.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_yaml = "0.9.27"
