name: "Thousand Moons Smithy"
types {
  legendary {
  }
}
types {
  artifact {
  }
}
cost {
  mana_costs {
    generic {
      count: 2
    }
  }
  mana_costs {
    white {
    }
  }
  mana_costs {
    white {
    }
  }
}
etb_abilities {
  create_token {
    creature {
      name: "Gnome Soldier"
      types {
        artifact {
        }
      }
      types {
        creature {
        }
      }
      subtypes {
        gnome {
        }
      }
      subtypes {
        soldier {
        }
      }
      dynamic_power_toughness {
        number_of_permanents_matching {
          controller {
            you {
            }
          }
          types {
            artifact {
            }
          }
          types {
            creature {
            }
          }
        }
      }
    }
  }
  oracle_text: "When Thousand Moons Smithy enters the battlefield, create a white Gnome Soldier artifact creature token with \"This creature\'s power and toughness are each equal to the number of artifacts and/or creatures you control.\""
}
triggered_abilities {
  trigger {
    source {
      pre_combat_main_phase {
      }
    }
    from {
      anywhere {
      }
    }
    controller {
      you {
      }
    }
  }
  effects {
    pay_cost_then {
      cost {
        additional_costs {
          tap_permanent {
            restrictions {
              of_type {
                types {
                  creature {
                  }
                }
                types {
                  artifact {
                  }
                }
              }
            }
          }
        }
        additional_costs {
          tap_permanent {
            restrictions {
              of_type {
                types {
                  creature {
                  }
                }
                types {
                  artifact {
                  }
                }
              }
            }
          }
        }
        additional_costs {
          tap_permanent {
            restrictions {
              of_type {
                types {
                  creature {
                  }
                }
                types {
                  artifact {
                  }
                }
              }
            }
          }
        }
        additional_costs {
          tap_permanent {
            restrictions {
              of_type {
                types {
                  creature {
                  }
                }
                types {
                  artifact {
                  }
                }
              }
            }
          }
        }
        additional_costs {
          tap_permanent {
            restrictions {
              of_type {
                types {
                  creature {
                  }
                }
                types {
                  artifact {
                  }
                }
              }
            }
          }
        }
      }
      effects {
        transform {
        }
      }
    }
  }
  oracle_text: "Transform Thousand Moons Smithy"
}
back_face {
  name: "Barracks of the Thousand"
  types {
    legendary {
    }
  }
  types {
    artifact {
    }
  }
  types {
    land {
    }
  }
  triggered_abilities {
    trigger {
      source {
        cast {
        }
      }
      from {
        anywhere {
        }
      }
      controller {
        you {
        }
      }
      restrictions {
        of_type {
          types {
            artifact {
            }
          }
          types {
            creature {
            }
          }
        }
      }
    }
    effects {
      create_token {
        creature {
          name: "Gnome Soldier"
          types {
            artifact {
            }
          }
          types {
            creature {
            }
          }
          subtypes {
            gnome {
            }
          }
          subtypes {
            soldier {
            }
          }
          dynamic_power_toughness {
            number_of_permanents_matching {
              controller {
                you {
                }
              }
              types {
                artifact {
                }
              }
              types {
                creature {
                }
              }
            }
          }
        }
      }
    }
    oracle_text: "Whenever you cast an artifact or creature spell using mana from Barracks of the Thousand, create a white Gnome Soldier artifact creature token with \"This creature's power and toughness are each equal to the number of artifacts and/or creatures you control.\""
  }
  mana_abilities {
    cost {
      tap: true
    }
    gain_mana {
      specific {
        gains {
          white {
          }
        }
      }
    }
    mana_source {
      barracks_of_the_thousand {
      }
    }
  }
}
