name: "Adaptive Gemguard"
types {
  artifact {
  }
}
types {
  creature {
  }
}
subtypes {
  gnome {
  }
}
cost {
  mana_costs {
    generic {
      count: 3
    }
  }
  mana_costs {
    white {
    }
  }
}
activated_abilities {
  cost {
    additional_costs {
      tap_permanent {
        restrictions {
          of_type {
            types {
              artifact {
              }
            }
            types {
              creature {
              }
            }
          }
        }
      }
    }
    additional_costs {
      tap_permanent {
        restrictions {
          of_type {
            types {
              artifact {
              }
            }
            types {
              creature {
              }
            }
          }
        }
      }
    }
  }
  effects {
    gain_counter {
      single {
        counter {
          p1p1 {
          }
        }
      }
    }
  }
  oracle_text: "Put a +1/+1 counter on Adpative Gemguard.\nActivate only as sourcery."
  sorcery_speed: true
}
power: 3
toughness: 3
