name: "Abuelo's Awakening"
cost {
  mana_costs { x{} }
  mana_costs { generic { count: 3 } }
  mana_costs { white {} }
}
types { sorcery {} }
oracle_text:  "Return target artifact or non-aura"
              " enchantment from your graveyard"
              " to the battlefield with X additional +1/+1"
              " counters on it. It's a 1/1 Spirit creature"
              " with flying in addition to its other types"
restrictions {
  of_type {
    types { artifact {} }
    types { enchantment {} }
  }
  not_of_type {
    subtypes { aura {} }
  }
}
effects {
  return_from_graveyard_to_battlefield {
    count: 1
  }
}
effects {
  target_gains_counters {
    dynamic { 
      x {
        counter { p1p1 {} }
      } 
    }
  }
}
effects {
  modify_target {
    modifier{ 
      base_power: 1
      base_toughness: 1
      add_types { creature {} }
      add_subtypes { spirit {} }
      add_keywords: "Flying"
    }
    controller { any{} }
    duration { until_target_leaves_battlefield {} }
  }
}