name: "Abzan Banner"
cost {
  mana_costs {
    generic {
      count: 3
    }
  }
}
types { artifact {} }
mana_gains {
  cost {
    tap: true
  }
  gain_mana {
    choice {
      choices { gains { white {} } }
      choices { gains { black {} } }
      choices { gains { green {} } }
    }
  }
}
activated_abilities {
  cost {
    mana_costs { white {} }
    mana_costs { black {} }
    mana_costs { green {} }
    tap: true
    additional_costs { sacrifice_this {} }
  }
  effects {
    controller_draw_cards {
      count: 1
    }
  }
  oracle_text: "Draw a card."
}
