name: "Acrobatic Leap"
cost {
  mana_costs { white {} }
}
effects {
  modify_creature {
    modifier {
      add_power: 1
      add_toughness: 3
      add_keywords: "Flying"
    }
  }
}
effects {
  untap_target {}
}
