name: "Allosaurus Shepherd"
types {
  creature {
  }
}
subtypes {
  elf {
  }
}
subtypes {
  shaman {
  }
}
cost {
  mana_costs {
    green {
    }
  }
}
cannot_be_countered: true
oracle_text: "This spell can\'t be countered.\nGreen spells you control can\'t be countered"
static_abilities {
  green_cannot_be_countered {
    restrictions {
      controller {
        self {
        }
      }
    }
  }
}
activated_abilities {
  cost {
    mana_costs {
      generic {
        count: 4
      }
    }
    mana_costs {
      green {
      }
    }
    mana_costs {
      green {
      }
    }
  }
  effects {
    battlefield_modifier {
      modifier {
        base_power: 5
        base_toughness: 5
        add_subtypes {
          dinosaur {
          }
        }
        entire_battlefield: true
      }
      duration {
        until_end_of_turn {
        }
      }
      restrictions {
        controller {
          self {
          }
        }
      }
      restrictions {
        of_type {
          subtypes {
            elf {
            }
          }
        }
      }
    }
  }
  oracle_text: "Until end of turn, each Elf creature you control has base power and toughness 5/5 and becomes a dinosaur in addition to its other creature types."
}
power: 1
toughness: 1
