name: "Annul"
types {
  instant {
  }
}
cost {
  mana_costs {
    blue {
    }
  }
  mana_costs {
    blue {
    }
  }
}
oracle_text: "Counter target artifact or enchantment spell."
effects {
  counter_spell {
    restrictions {
      of_type {
        types {
          artifact {
          }
        }
        types {
          enchantment {
          }
        }
      }
    }
  }
}
