name: "Annul"
cost {
  mana_costs { blue {} }
  mana_costs { blue {} }
}
ty { instant {} }
oracle_text: "Counter target spell."
effects {
  counter_spell {
    target { 
      types { artifact {} }
      types { enchantment {} }
    }
  }
}
targets { spell {} }
