name: "Annul"
cost {
  mana_costs { blue {} }
  mana_costs { blue {} }
}
types { instant {} }
oracle_text: "Counter target artifact or enchantment spell."
effects {
  counter_spell {
    valid_target { 
      types { artifact {} }
      types { enchantment {} }
    }
  }
}
