name: "Mountain"
cost { }
types { basic_land {} }
subtypes { mountain {} }
activated_abilities {
  cost {
    tap: true
  }
  effects {
    gain_mana {
      specific { gains { red {} } }
    }
  }
}
