name: "Blasting Station"
cost {
  mana_costs { generic{count: 3} }
}
types { artifact{} }
activated_abilities {
  cost {
    tap: true
    additional_costs {
      sacrifice_permanent {
        restrictions { of_type { types { creature {} } } }
      }
    }
  }
  effects {
    deal_damage {
      quantity: 1
    }
  }
}
triggered_abilities {
  trigger {
    source { enters_the_battlefield {} }
    from { anywhere {} }
    types { creature {} }
  }
  effects {
    untap_this {}
  }
  oracle_text:  "Whenever a creature enters the battlefield"
                " you may untap blasting station."
}