name: "Bog Initiate"
cost { 
  mana_costs { generic { count: 1 } }
  mana_costs { black {} }
}
types { creature{} }
subtypes { human {} }
subtypes { wizard {} }
oracle_text: "{1}: Add {B}"
mana_abilities {
  cost {
    mana_costs { generic { count: 1 } }
  }
  gain_mana {
    specific {
      gains { black{} }
    }
  }
}