name: "Cosmium Blast"
types {
  instant {
  }
}
cost {
  mana_costs {
    generic {
      count: 1
    }
  }
  mana_costs {
    white {
    }
  }
}
oracle_text: "Cosmium Blast deals 4 damage to target attacking or blocking creature."
effects {
  deal_damage {
    quantity: 4
  }
}
restrictions {
  of_type {
    types {
      creature {
      }
    }
  }
}
restrictions {
  attacking_or_blocking {
  }
}
restrictions {
  on_battlefield {
  }
}
