name: "Darigaaz\'s Attendant"
types {
  artifact {
  }
}
types {
  creature {
  }
}
subtypes {
  golem {
  }
}
cost {
  mana_costs {
    generic {
      count: 5
    }
  }
}
oracle_text: "{1}, Sacrifice Darigaaz\'s Attendant: Add {B}{R}{G}."
mana_abilities {
  cost {
    mana_costs {
      generic {
        count: 1
      }
    }
    additional_costs {
      sacrifice_source {
      }
    }
  }
  gain_mana {
    specific {
      gains {
        black {
        }
      }
      gains {
        red {
        }
      }
      gains {
        green {
        }
      }
    }
  }
}
