name: "Elesh Norn, Grand Cenobite"
types {
  legendary {
  }
}
types {
  creature {
  }
}
subtypes {
  praetor {
  }
}
cost {
  mana_costs {
    generic {
      count: 5
    }
  }
  mana_costs {
    white {
    }
  }
  mana_costs {
    white {
    }
  }
}
oracle_text: "Vigilance\nOther creatures you control get +2/+2\nCreatures your opponents control get -2/-2\n"
static_abilities {
  battlefield_modifier {
    modifier {
      add_power: 2
      add_toughness: 2
      entire_battlefield: true
    }
    duration {
      until_source_leaves_battlefield {
      }
    }
    restrictions {
      controller {
        self {
        }
      }
    }
    restrictions {
      not_self {
      }
    }
  }
}
static_abilities {
  battlefield_modifier {
    modifier {
      add_power: -2
      add_toughness: -2
      entire_battlefield: true
    }
    duration {
      until_source_leaves_battlefield {
      }
    }
    restrictions {
      controller {
        opponent {
        }
      }
    }
    restrictions {
      not_self {
      }
    }
  }
}
power: 4
toughness: 7
keywords: "Vigilance"
