name: "Envoy of Okinec Ahau"
cost {
  mana_costs {
    generic {
      count: 2
    }
  }
  mana_costs {
    white {
    }
  }
}
activated_abilities {
  cost {
    mana_costs {
      generic {
        count: 4
      }
    }
    mana_costs {
      white {
      }
    }
  }
  effects {
    create_token {
      creature {
        name: "Gnome"
        types {
          artifact {
          }
        }
        types {
          creature {
          }
        }
        subtypes {
          gnome {
          }
        }
        power: 1
        toughness: 1
      }
    }
  }
}
