name: "Get Lost"
types {
  instant {
  }
}
cost {
  mana_costs {
    generic {
      count: 1
    }
  }
  mana_costs {
    white {
    }
  }
}
oracle_text: "Destroy target creature, enchantment, or planeswalker. Its controller creates two map tokens."
effects {
  destroy_target {
    restrictions {
      of_type {
        types {
          creature {
          }
        }
        types {
          enchantment {
          }
        }
        types {
          planeswalker {
          }
        }
      }
    }
  }
}
effects {
  target_controller_gains_tokens {
    map {
    }
  }
}
effects {
  target_controller_gains_tokens {
    map {
    }
  }
}
