name: "Hoar Shade"
cost {
  mana_costs { generic { count: 3 } }
  mana_costs { black {} }
}
types { creature {} }
subtypes { shade {} }
oracle_text: "{B}: Hoar Shad gets +1/+1 until end of turn"
activated_abilities {
  cost {
    mana_costs { black {} }
  }
  effects {
    battlefield_modifier { 
      modifier {
        add_power: 1
        add_toughness: 1
      }
      controller { you {} }
      duration { until_end_of_turn {} }
    }
  }
  apply_to_self: true
}
power: 1
toughness: 2