name: "Hoar Shade"
types {
  creature {
  }
}
subtypes {
  shade {
  }
}
cost {
  mana_costs {
    generic {
      count: 3
    }
  }
  mana_costs {
    black {
    }
  }
}
activated_abilities {
  cost {
    mana_costs {
      black {
      }
    }
  }
  effects {
    battlefield_modifier {
      modifier {
        add_power: 1
        add_toughness: 1
      }
      controller {
        you {
        }
      }
      duration {
        until_end_of_turn {
        }
      }
    }
  }
  apply_to_self: true
  oracle_text: "Hoar Shade gets +1/+1 until end of turn"
}
power: 1
toughness: 2
