name: "King Crab"
cost {
  mana_costs { generic { count: 4 } }
  mana_costs { blue {} }
  mana_costs { blue {} }
}
activated_abilities {
  cost { 
    mana_costs { generic { count: 1 } }
    mana_costs { blue {} }
    tap: true
  }
  effects {
    target_to_top_of_library {
      restrictions {
        of_type { types { creature {} } }
      }
      restrictions { of_color { colors { green {} } } }
    }
  }
  oracle_text: "Put target green creature on top of its owner's library"
}