name: "Kinjalli\'s Dawnrunner"
types {
  creature {
  }
}
subtypes {
  human {
  }
}
subtypes {
  scout {
  }
}
cost {
  mana_costs {
    generic {
      count: 3
    }
  }
  mana_costs {
    white {
    }
  }
}
etb_abilities {
  self_explores {
  }
}
power: 1
toughness: 1
keywords: "DoubleStrike"
