name: "Krosan Verge"
types { land {} }
etb_tapped: true
mana_abilities {
  cost {
    tap: true
  }
  gain_mana {
    specific { gains{ colorless{} } }
  }
}
activated_abilities {
  cost {
    mana_costs { generic { count: 2 } }
    additional_costs{ sacrifice_this{} } 
    tap: true
  }
  effects {
    tutor_library {
      restrictions { 
        of_type { subtypes { forest {} } }
      }
      destination { battlefield { enters_tapped: true } }
    }
  }
  effects {
    tutor_library {
      restrictions { 
        of_type { subtypes { plains {} } }
      }
      destination { battlefield { enters_tapped: true } }
    }
  }
  oracle_text:  "Search your library for a Forest card and a Plains cards, "
                "put them onto the battlefield tapped, then shuffle."
}
