name: "Market Gnome"
types {
  artifact {
  }
}
types {
  creature {
  }
}
subtypes {
  gnome {
  }
}
cost {
  mana_costs {
    white {
    }
  }
}
triggered_abilities {
  trigger {
    source {
      put_into_graveyard {
      }
    }
    from {
      battlefield {
      }
    }
    restrictions {
      controller {
        self {
        }
      }
    }
    restrictions {
      self {
      }
    }
  }
  effects {
    gain_life {
      count: 1
    }
  }
  effects {
    controller_draw_cards {
      count: 1
    }
  }
}
triggered_abilities {
  trigger {
    source {
      exiled_during_craft {
      }
    }
    from {
      battlefield {
      }
    }
    restrictions {
      controller {
        self {
        }
      }
    }
    restrictions {
      self {
      }
    }
  }
  effects {
    gain_life {
      count: 1
    }
  }
  effects {
    controller_draw_cards {
      count: 1
    }
  }
}
power: 0
toughness: 3
