name: "Ojer Taq, Deepest Foundation"
types {
  legendary {
  }
}
types {
  creature {
  }
}
subtypes {
  god {
  }
}
cost {
  mana_costs {
    generic {
      count: 4
    }
  }
  mana_costs {
    white {
    }
  }
  mana_costs {
    white {
    }
  }
}
triggered_abilities {
  trigger {
    source {
      put_into_graveyard {
      }
    }
    from {
      battlefield {
      }
    }
    restrictions {
      controller {
        self {
        }
      }
    }
    restrictions {
      self {
      }
    }
  }
  effects {
    return_transformed {
    }
  }
  oracle_text: "When Ojer Taq dies, return it to the battlefield tapped and transformed under its owner\'s control."
}
replacement_effects {
  token_creation {
  }
  restrictions {
    controller {
      self {
      }
    }
  }
  restrictions {
    of_type {
      types {
        creature {
        }
      }
    }
  }
  effects {
    multiply_tokens {
      multiplier: 3
    }
  }
}
power: 6
toughness: 6
keywords: "Vigilance"
back_face {
  name: "Temple of Civilization"
  types {
    land {
    }
  }
  activated_abilities {
    cost {
      mana_costs {
        generic {
          count: 2
        }
      }
      mana_costs {
        white {
        }
      }
      tap: true
      restrictions {
        attacked_with_x_or_more_creatures {
          x_is: 3
        }
      }
    }
    effects {
      transform {
      }
    }
    oracle_text: "Transform Temple of Civilization. Activate only if you attacked with three or more creatures this turn and only as sorcery."
    sorcery_speed: true
  }
  mana_abilities {
    cost {
      tap: true
    }
    gain_mana {
      specific {
        gains {
          white {
          }
        }
      }
    }
  }
}
