name: "Oltec Cloud Guard"
types {
  creature {
  }
}
subtypes {
  human {
  }
}
subtypes {
  soldier {
  }
}
cost {
  mana_costs {
    generic {
      count: 3
    }
  }
  mana_costs {
    white {
    }
  }
}
etb_abilities {
  create_token {
    creature {
      name: "Gnome"
      types {
        creature {
        }
      }
      types {
        artifact {
        }
      }
      subtypes {
        gnome {
        }
      }
      power: 1
      toughness: 1
    }
  }
}
power: 3
toughness: 2
keywords: "Flying"
