name: "Paradise Mantle"
types {
  artifact {
  }
}
subtypes {
  equipment {
  }
}
cost {
  mana_costs {
    generic {
    }
  }
}
oracle_text: "Equipped creature has \"{T}: Add one mana of any color.\""
activated_abilities {
  cost {
    mana_costs {
      generic {
        count: 1
      }
    }
  }
  effects {
    equip {
      modifiers {
        mana_ability {
          cost {
            tap: true
          }
          gain_mana {
            choice {
              choices {
                gains {
                  white {
                  }
                }
              }
              choices {
                gains {
                  blue {
                  }
                }
              }
              choices {
                gains {
                  black {
                  }
                }
              }
              choices {
                gains {
                  red {
                  }
                }
              }
              choices {
                gains {
                  green {
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  oracle_text: "Equip"
}
