name: "+2 Mace"
cost {
  mana_costs { generic { count: 1 }}
  mana_costs { white {} }
}
types { artifact {} }
subtypes { equipment {} }
oracle_text: "Equipped creature gets +2/+2"
activated_abilities {
  cost { mana_costs { generic { count: 3 } } }
  effects {
    equip {
      modifiers {
        add_power: 2
        add_toughness: 2
      }
    }
  }
}
