name: "Queen\'s Commission"
types {
  sorcery {
  }
}
oracle_text: "Create two 1/1 white Vampire creature tokens with lifelink."
effects {
  create_token {
    creature {
      name: "Vampire"
      types {
        creature {
        }
      }
      subtypes {
        vampire {
        }
      }
      colors {
        white {
        }
      }
      power: 1
      toughness: 1
    }
  }
}
effects {
  create_token {
    creature {
      name: "Vampire"
      types {
        creature {
        }
      }
      subtypes {
        vampire {
        }
      }
      colors {
        white {
        }
      }
      power: 1
      toughness: 1
    }
  }
}
