name: "Thermal Blast"
types {
  instant {
  }
}
cost {
  mana_costs {
    generic {
      count: 4
    }
  }
  mana_costs {
    red {
    }
  }
}
oracle_text: "Thermal Blast deals 3 damage to target creature.\nThreshold \024 Thermal Blast deals 5 damage instead if seven or more cards are in your graveyard."
effects {
  deal_damage {
    quantity: 3
    restrictions {
      of_type {
        types {
          creature {
          }
        }
      }
    }
  }
  threshold {
    deal_damage {
      quantity: 5
      restrictions {
        of_type {
          types {
            creature {
            }
          }
        }
      }
    }
  }
}
