name: "Thousand Moons Infantry"
types {
  creature {
  }
}
subtypes {
  human {
  }
}
subtypes {
  soldier {
  }
}
cost {
  mana_costs {
    generic {
      count: 2
    }
  }
  mana_costs {
    white {
    }
  }
}
static_abilities {
  untap_each_untap_step {
  }
}
power: 2
toughness: 4
