name: "Thousand Moons Crackshot"
types {
  creature {
  }
}
subtypes {
  human {
  }
}
subtypes {
  soldier {
  }
}
cost {
  mana_costs {
    generic {
      count: 1
    }
  }
  mana_costs {
    white {
    }
  }
}
triggered_abilities {
  trigger {
    source {
      attacks {
      }
    }
    from {
      anywhere {
      }
    }
    restrictions {
      controller {
        self {
        }
      }
    }
    restrictions {
      self {
      }
    }
  }
  effects {
    pay_cost_then {
      cost {
        mana_costs {
          generic {
            count: 2
          }
        }
        mana_costs {
          white {
          }
        }
      }
      effects {
        tap_target {
          restrictions {
            of_type {
              types {
                creature {
                }
              }
            }
          }
        }
      }
    }
  }
  oracle_text: "Whenever Thousand Moons Crackshot attacks, you may pay {2}{W}. When you do, tap target creature."
}
power: 2
toughness: 2
