name: "Titania, Protector of Argoth"
cost {
  mana_costs { generic { count: 3 } }
  mana_costs { green{} }
  mana_costs { green{} }
}
types { legendary {} }
types { creature {} }
subtypes { elemental {} }
oracle_text:  "When Titania, Protector of Argoth"
              "enters the battlefield, return target"
              "land card from your graveyard to the"
              "battlefield.\n"
              "Whenever a land you control is put"
              "into a graveyard from the battlefield,"
              "create a 5/3 green Elemental creature"
              "token."
power: 5
toughness: 3
etb_abilities {
  return_from_graveyard_to_battlefield {
    count: 1
    types { land {} }
    types { basic_land {} }
  }
}
triggered_abilities {
  trigger {
    put_into_graveyard {
      from { battlefield {} }
      types { land {} }
      types { basic_land {} }
    }
  }
  effects {
    create_token {
      creature {
        name: "Elemental"
        subtypes { elemental {} }
        colors { green {} }
        power: 5
        toughness: 3
      }
    }
  }
}