name: "Kutzil\'s Flanker"
types {
  creature {
  }
}
subtypes {
  cat {
  }
}
subtypes {
  warrior {
  }
}
cost {
  mana_costs {
    generic {
      count: 2
    }
  }
  mana_costs {
    white {
    }
  }
}
etb_abilities {
  modal {
    modes {
      effects {
        target_gains_counters {
          dynamic {
            left_battlefield_this_turn {
              restrictions {
                of_type {
                  types {
                    creature {
                    }
                  }
                }
              }
              controller {
                you {
                }
              }
            }
          }
          counter {
            p1p1 {
            }
          }
          restrictions {
            self {
            }
          }
        }
        oracle_text: "Put a +1/+1 counter on Kutzil\'s Flanker for each creature that left the battlefield under your control this turn."
      }
    }
    modes {
      effects {
        gain_life {
          count: 2
        }
        oracle_text: "You gain 2 life"
      }
      effects {
        scry {
          count: 2
        }
        oracle_text: "You scry 2"
      }
    }
    modes {
      effects {
        exile_target_graveyard {
        }
        oracle_text: "Exile target player\'s graveyard."
      }
    }
  }
  oracle_text: "When Kutzil\'s Flanker enters the battlefield choose one -\n- Put a +1/+1 counter on Kutzil\'s Flanker for each creature that left the battlefield under your control this turn.\n- You gain 2 life and scry 2.\n- Exile target player\'s graveyard."
}
power: 3
toughness: 1
keywords: "Flash"
