name: "Petrify"
types {
  enchantment {
  }
}
subtypes {
  aura {
  }
}
cost {
  mana_costs {
    generic {
      count: 1
    }
  }
  mana_costs {
    white {
    }
  }
}
enchant {
  modifiers {
    modifier {
      add_static_abilities {
        prevent_attacks {
        }
      }
      add_static_abilities {
        prevent_blocks {
        }
      }
      add_static_abilities {
        prevent_ability_activation {
        }
      }
    }
    controller {
      any {
      }
    }
    duration {
      until_source_leaves_battlefield {
      }
    }
  }
}
restrictions {
  of_type {
    types {
      creature {
      }
    }
    types {
      artifact {
      }
    }
  }
}
