name: "Majestic Metamorphosis"
types {
  instant {
  }
}
cost {
  mana_costs {
    generic {
      count: 2
    }
  }
  mana_costs {
    blue {
    }
  }
}
effects {
  modify_target {
    modifier {
      base_power: 4
      base_toughness: 4
      add_types {
        creature {
        }
      }
      add_types {
        artifact {
        }
      }
      add_subtypes {
        angel {
        }
      }
      add_keywords: "Flying"
    }
    controller {
      any {
      }
    }
    duration {
      until_end_of_turn {
      }
    }
    restrictions {
      of_type {
        types {
          creature {
          }
        }
        types {
          artifact {
          }
        }
      }
    }
  }
  oracle_text: "Until end of turn, target artifact or creature becomes a 4/4 Angel artifact creature and gains flying."
}
effects {
  controller_draw_cards {
    count: 1
  }
  oracle_text: "Draw a card"
}
restrictions {
  on_battlefield {
  }
}
