name: "Mischievous Pup"
types {
  creature {
  }
}
subtypes {
  dog {
  }
}
etb_abilities {
  return_target_to_hand {
    controller {
      you {
      }
    }
    restrictions {
      not_self {
      }
    }
    restrictions {
      on_battlefield {
      }
    }
  }
}
power: 3
toughness: 1
keywords: "Flash"
