name: "Sanguine Evangelist"
types {
  creature {
  }
}
subtypes {
  vampire {
  }
}
subtypes {
  cleric {
  }
}
cost {
  mana_costs {
    generic {
      count: 2
    }
  }
  mana_costs {
    white {
    }
  }
}
etb_abilities {
  create_token {
    creature {
      name: "Bat"
      types {
        creature {
        }
      }
      subtypes {
        bat {
        }
      }
      colors {
        black {
        }
      }
      power: 1
      toughness: 1
    }
  }
  oracle_text: "When Sanguine Evangelist enters the battlefield or dies, create a 1/1 black Bat creature token with flying."
}
triggered_abilities {
  trigger {
    source {
      put_into_graveyard {
      }
    }
    from {
      battlefield {
      }
    }
    restrictions {
      controller {
        self {
        }
      }
    }
    restrictions {
      self {
      }
    }
  }
  effects {
    create_token {
      creature {
        name: "Bat"
        types {
          creature {
          }
        }
        subtypes {
          bat {
          }
        }
        colors {
          black {
          }
        }
        power: 1
        toughness: 1
      }
    }
  }
  oracle_text: "When Sanguine Evangelist enters the battlefield or dies, create a 1/1 black Bat creature token with flying."
}
power: 2
toughness: 1
keywords: "BattleCry"
