name: "Family Reunion"
types {
  instant {
  }
}
cost {
  mana_costs {
    generic {
      count: 1
    }
  }
  mana_costs {
    white {
    }
  }
}
modes {
  effects {
    battlefield_modifier {
      modifier {
        add_power: 1
        add_toughness: 1
        entire_battlefield: true
      }
      controller {
        you {
        }
      }
      duration {
        until_end_of_turn {
        }
      }
      restrictions {
        of_type {
          types {
            creature {
            }
          }
        }
      }
    }
    oracle_text: "Creatures you control get +1/+1 until end of turn."
  }
}
modes {
  effects {
    battlefield_modifier {
      modifier {
        entire_battlefield: true
        add_keywords: "Hexproof"
      }
      controller {
        you {
        }
      }
      duration {
        until_end_of_turn {
        }
      }
      restrictions {
        of_type {
          types {
            creature {
            }
          }
        }
      }
    }
    oracle_text: "Creatures you control gain hexproof until end of turn."
  }
}
