name: "Blood Scrivener"
types {
  creature {
  }
}
subtypes {
  zombie {
  }
}
subtypes {
  wizard {
  }
}
cost {
  mana_costs {
    generic {
      count: 1
    }
  }
  mana_costs {
    black {
    }
  }
}
oracle_text: "If you would draw a card while you have no cards in hand, instead you draw two cards and you lose 1 life."
replacement_effects {
  draw {
  }
  controller {
    you {
    }
  }
  restrictions {
    controller_hand_empty {
    }
  }
  effects {
    controller_draw_cards {
      count: 2
    }
  }
  effects {
    controller_loses_life {
      count: 1
    }
  }
}
power: 2
toughness: 1
