name: "Ironpaw Aspirant"
types {
  creature {
  }
}
subtypes {
  cat {
  }
}
subtypes {
  warrior {
  }
}
cost {
  mana_costs {
    generic {
      count: 1
    }
  }
  mana_costs {
    white {
    }
  }
}
etb_abilities {
  target_gains_counters {
    single {
    }
    counter {
      p1p1 {
      }
    }
    restrictions {
      of_type {
        types {
          creature {
          }
        }
      }
    }
    restrictions {
      on_battlefield {
      }
    }
  }
  oracle_text: "When Ironpaw Aspirant enters the battlefield, put a +1/+1 counter on target creature."
}
power: 1
toughness: 2
