name: "Zhulodok, Void Gorger"
types {
  legendary {
  }
}
types {
  creature {
  }
}
subtypes {
  eldrazi {
  }
}
cost {
  mana_costs {
    generic {
      count: 5
    }
  }
  mana_costs {
    colorless {
    }
  }
}
static_abilities {
  battlefield_modifier {
    modifier {
      global: true
      add_keywords: "Cascade, Cascade"
    }
    controller {
      you {
      }
    }
    duration {
      until_source_leaves_battlefield {
      }
    }
    restrictions {
      of_color {
        colors {
          colorless {
          }
        }
      }
    }
    restrictions {
      cmc {
        comparison {
          greater_than_or_equal {
            value: 7
          }
        }
      }
    }
    restrictions {
      cast_from_hand {
      }
    }
  }
}
power: 7
toughness: 4
