name: "Glorifier of Suffering"
types {
  creature {
  }
}
subtypes {
  vampire {
  }
}
subtypes {
  soldier {
  }
}
cost {
  mana_costs {
    generic {
      count: 2
    }
  }
  mana_costs {
    white {
    }
  }
}
target_individually: true
etb_abilities {
  pay_cost_then {
    cost {
      additional_costs {
        sacrifice_permanent {
          restrictions {
            of_type {
              types {
                artifact {
                }
              }
              types {
                creature {
                }
              }
            }
          }
        }
      }
    }
    effects {
      target_gains_counters {
        single {
        }
        counter {
          p1p1 {
          }
        }
        restrictions {
          of_type {
            types {
              creature {
              }
            }
          }
        }
        restrictions {
          on_battlefield {
          }
        }
      }
      oracle_text: "Put a +1/+1 counter on target creature"
    }
    effects {
      target_gains_counters {
        single {
        }
        counter {
          p1p1 {
          }
        }
        restrictions {
          of_type {
            types {
              creature {
              }
            }
          }
        }
        restrictions {
          on_battlefield {
          }
        }
      }
      oracle_text: "Put a +1/+1 counter on target creature"
    }
  }
  oracle_text: "When Glorifier of Suffering enters the battlefield, you may sacrifice another creature or artifact. When you do, put a +1/+1 counter on each of up to two target creatures."
}
power: 3
toughness: 2
