name: "Quicksand Whirlpool"
types {
  instant {
  }
}
cost {
  mana_costs {
    generic {
      count: 5
    }
  }
  mana_costs {
    white {
    }
  }
}
cost_reducer {
  target_tapped_creature {
  }
  reduction {
    generic {
      count: 3
    }
  }
}
oracle_text: "This spell costs {3} less to cast if it targets a tapped creature\nExile target creature."
effects {
  exile_target {
    restrictions {
      of_type {
        types {
          creature {
          }
        }
      }
    }
    restrictions {
      on_battlefield {
      }
    }
    controller {
      any {
      }
    }
    duration {
      permanently {
      }
    }
  }
}
