name: "Resplendent Angel"
types {
  creature {
  }
}
subtypes {
  angel {
  }
}
cost {
  mana_costs {
    generic {
      count: 1
    }
  }
  mana_costs {
    white {
    }
  }
  mana_costs {
    white {
    }
  }
}
activated_abilities {
  cost {
    mana_costs {
      generic {
        count: 3
      }
    }
    mana_costs {
      white {
      }
    }
    mana_costs {
      white {
      }
    }
    mana_costs {
      white {
      }
    }
  }
  effects {
    battlefield_modifier {
      modifier {
        add_power: 2
        add_toughness: 2
        add_keywords: "Lifelink"
      }
      controller {
        you {
        }
      }
      duration {
        until_end_of_turn {
        }
      }
      restrictions {
        self {
        }
      }
    }
  }
  apply_to_self: true
  oracle_text: "Until end of turn, Resplendent Angel gets +2/+2 and gains lifelink."
}
triggered_abilities {
  trigger {
    source {
      end_step {
      }
    }
    from {
      anywhere {
      }
    }
    controller {
      any {
      }
    }
    restrictions {
      life_gained_this_turn {
        count: 5
      }
    }
  }
  effects {
    create_token {
      creature {
        name: "Angel"
        types {
          creature {
          }
        }
        subtypes {
          angel {
          }
        }
        colors {
          white {
          }
        }
        power: 4
        toughness: 4
        keywords: "Flying, Vigilance"
      }
    }
  }
  oracle_text: "At the beginning of each end step, if you gained 5 or more life this turn, create a 4/4 white Angel creature token with flying and vigilance."
}
power: 3
toughness: 3
keywords: "Flying"
